[package]
name = "gossip-glommers"
version = "0.1.0"
edition = "2021"

[dependencies]
serde ={ version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["full"] }
